name: obl_taller_ia
channels:
  - microsoft
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.12
  - conda-forge::pytorch
  - conda-forge::jupyter
  - conda-forge::torchinfo
  - conda-forge::numpy
  - conda-forge::matplotlib
  - conda-forge::tqdm
  - conda-forge::pygame
  - conda-forge::gymnasium-box2d
  - conda-forge::gymnasium-other
  - conda-forge::gymnasium=1.0.0
  - pip
  - pip:
      - highway-env
