_wandb:
    value:
        cli_version: 0.21.3
        e:
            4ner9b8sy8gx3ahl2j2qywgfsto05yhw:
                codePath: Deep Learning/Taller de DL/Clase 02 - California House Price-20250903/California_House-letra.ipynb
                codePathLocal: California_House-letra.ipynb
                email: rodrigo.benitezacosta@gmail.com
                executable: /Users/rodrigobenitez/Documents/GitHub/ORT-AI/.venv/bin/python
                git:
                    commit: 8a0f25924a1268a0d8742ecdb72f09de43939060
                    remote: https://github.com/rodrigobeniteza/ORT-AI.git
                host: MBP-00706
                os: macOS-15.6.1-arm64-arm-64bit-Mach-O
                program: /Users/rodrigobenitez/Documents/GitHub/ORT-AI/Deep Learning/Taller de DL/Clase 02 - California House Price-20250903/California_House-letra.ipynb
                python: CPython 3.13.1
                root: /Users/rodrigobenitez/Documents/GitHub/ORT-AI/Deep Learning/Taller de DL/Clase 02 - California House Price-20250903
                startedAt: "2025-09-06T18:33:27.323339Z"
                writerId: 4ner9b8sy8gx3ahl2j2qywgfsto05yhw
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 14
            "4": 3.13.1
            "5": 0.21.3
            "8":
                - 1
            "12": 0.21.3
            "13": darwin-arm64
batch_size:
    value: 256
learning_rate:
    value: 0.06412249143403953
optimizer:
    value: adam
