name: taller-dl
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - ipykernel
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.1
  - numpy
  - scikit-learn
  - matplotlib
  - pandas
  - nltk
  - kaggle
  - pip
  - pip:
    - torchinfo
    - wandb